build:
    version: "2.0"

accounts:
    message: "Welcome to Bank accounts related QA APIs "
    contactDetails:
      name: "Naveenkumar - Quality Assurance"
      email: "naveen@.com"
    onCallSupport:
      - (555) 555-1234
      - (555) 523-1345