build:
    version: "1.0"

 accounts:
    message: "Welcome to Bank accounts related local prod APIs "
    contactDetails:
      name: "Naveenkumar - production manager"
      email: "naveen@.com"
    onCallSupport:
      - (555) 555-1234
       -(555) 523-1345